name: audio_route
description: Flutter plugin to get all the information about the device audio routes.
version: 1.0.3
homepage: https://github.com/yisusdevp/audio_route

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: yisusdevp.flutter.audio_route
        pluginClass: AudioRoutePlugin
      ios:
        pluginClass: AudioRoutePlugin
